apiVersion: v1
kind: ConfigMap
metadata:
  name: archburgers-db-access-config
data:
  "archburgers.datasource-mongodb.uri": "{DB_MONGODB_URI}"
  "archburgers.datasource-mongodb.database": "{DB_MONGODB_DATABASE}"