apiVersion: v1
kind: Service
metadata:
  name: archburgers-svc-pagamento-internal
spec:
  selector:
    app: archburgers-svc-pagamento
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
